baseurl                  = "https://www.owing.cc"           # Your domain name
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "A new Fintech news site"
theme                    = "hugo-theme-sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
googleAnalytics          = "UA-163481766-1"                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    # favicon              = "sam.ico"
    homepage             = "main"                           # What to call the home page link
    footerText           = "A new Fintech news site."

# Metadata for Open Graph and Twitter
    description          = "A new Fintech news site."               # Max 160 characters show in search results
    # images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Search us"

[[params.mainMenu]]
    link = "posts"
    text = "posts"

[[params.mainMenu]]
    link = "about"
    text = "who owns this site?"

[imaging]
    quality = 75

[[params.mainMenu]]
    text = "bounty.show"
    link = "https://www.bounty.show/"
[[params.mainMenu]]
    text = "FIX API"
    link = "https://www.fixapi.org/"
